version: "3"

services:
  web:
      container_name: "myserver-app"
      restart: always
      build: .
      ports: 
        - "5001:5000"
      links:
        - mongo
      volumes:
        - .:/usr/src/app
  mongo:
      container_name: "mydatabase-app"
      image: mongo
      # environment:
      #   - MONGO_INITDB_DATABASE=tutorials
      #   - MONGO_INITDB_ROOT_USERNAME=root
      #   - MONGO_INITDB_ROOT_PASSWORD=test
      ports:
        - "27018:27017"
      volumes:
        - ./src/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro